### ISSUE TITLE
feat: implement build checks using github actions

### ISSUE THREAD

**Issue by slayerjain** [keploy/go-sdk#116]
**Is your feature request related to a problem? Please describe.**
There are currently no checks if the SDK is building correctly. This should be a minimum requirement before merging to the `main` branch. 

**Describe the solution you'd like**
A Github actions pipeline that automatically checks if the SDK is being built correctly. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by khanjasir90** [comment]
@slayerjain I would love to work on this but... ig using github actions would require elevated privilege for the contributor?

**Comment by khanjasir90** [comment]
any updates on this issue @slayerjain ?

**Comment by slayerjain** [comment]
Would it be possible to run the pipeline in your fork first? For eg: between forks? 

Then you can do a PR, and we would approve running the pipeline.

**Comment by khanjasir90** [comment]
@slayerjain ok will try and get back to u

**Comment by re-Tick** [comment]
Merged changes for this issue in #125. Closing this issue
