### ISSUE TITLE
feat : need to add keploy's record and replay for grpc-server

### ISSUE THREAD

**Issue by iamskp99** [keploy/go-sdk#147]
**Is your feature request related to a problem? Please describe.**

Keploy has integration for grpc client but it doesn't have support for the grpc-server.

**Describe the solution you'd like**

We can use UranaryServer interceptor for intercepting grpc calls and for simulating it we can use [grpcurl.](https://github.com/fullstorydev/grpcurl)

**Describe alternatives you've considered**

**Additional context**

**Comment by re-Tick** [comment]
Merged the changes. Closing this issue
