### ISSUE TITLE
no new tests should be generated in test mode

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/go-sdk#155]
**Describe the bug**
- When we run our application's existing keploy tests, and if we try to hit an API call, it will generate a new test case. Since it is in test mode so no new tests should be generated even if there is some API call.

**To Reproduce**
1. Integrate go-SDK with your application & set KEPLOY_MODE=record
2. Run your application, and record some test cases.
3. Run the application again but in KEPLOY_MODE=test.
4. When tests are running, hit an API call.

**Comment by PranshuSrivastava** [comment]
I want to wortk on this

**Comment by re-Tick** [comment]
Closing this issue.
