### ISSUE TITLE
feat: Export Keploy Context

### ISSUE THREAD

**Issue by jiawchong** [keploy/go-sdk#170]
**Is your feature request related to a problem? Please describe.**
The current router that I have is not supported in Keploy integration, thus I want to write my own function to construct the Keploy Context based on Test_ID and inject it to my own functions.

**Describe the solution you'd like**
Export the Keploy Context by moving it out of the /internal folder so that I can access and construct my own Keploy Context to be injected into my functions.

**Comment by slayerjain** [comment]
@jiawchong you should be able to use the Keploy Context now.

**Comment by jiawchong** [comment]
thanks @slayerjain  appreciate your help :)
