### ISSUE TITLE
Add configuration method for http client to integrate with keploy/sdk.

### ISSUE THREAD

**Issue by re-Tick** [keploy/go-sdk#32]
**Is your feature request related to a problem? Please describe.**
I am using net/http package for my API as external dependency(http.Client). It is not capturing its outputs in dependencies array.

**Describe the solution you'd like**
Please add support for http.Client of net/http package and provide its documentation.

Hope to have documentation for net/http support soon.

**Comment by slayerjain** [comment]
@re-Tick is this done?

**Comment by re-Tick** [comment]
Added an interceptor for httpCLient in PR #69.
