### ISSUE TITLE
Avoid importing all drivers from Integration

### ISSUE THREAD

**Issue by slayerjain** [keploy/go-sdk#37]
**Is your feature request related to a problem? Please describe.**
Currently, if any integration package is imported into an application, all the other integration drivers also imported. We need to ensure only used integrations are imported. 

**Describe the solution you'd like**
Avoid importing unnecessary packages

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by Sarthak160** [comment]
Yes sure
