### ISSUE TITLE
Implement filters for testcase capture in sdk

### ISSUE THREAD

**Issue by Sarthak160** [keploy/go-sdk#56]
**Is your feature request related to a problem? Please describe.**
The SDK should implement filters for testcase capture- https://github.com/keploy/keploy/issues/28

**Describe the solution you'd like**
Adding an option for regex filter in App Config and implementing it while recording testcases

**Additional context**
single regex filter would do the needful , can implement for multiple expressions too 

**Describe alternatives you've considered**
NA

**Comment by slayerjain** [comment]
Here only URL filters have been implemented. Other filters are still pending.

**Comment by CannibalVox** [comment]
I'm interested in this feature- I work on a product that interacts with credit card processors, and it would be good if we could filter request & response on test cases and captures to replace real credit card numbers with fake ones.

**Comment by Sarthak160** [comment]
@CannibalVox  You can add some more like filtering by headers just like I did for url . You can refer #58 and add field in **Filter** struct

**Comment by petergeorgas** [comment]
Did this ever end up going anywhere? Perhaps I could work on it if nobody has made any progress?

**Comment by slayerjain** [comment]
thanks for your interest. I believe Raj is working on this one. @nehagup can you please tag raj here? 

@petergeorgas I've tagged with you an issue you may be interested in. Please let me know if you'd like to try something else or have any questions 👯

**Comment by RajGM** [comment]
Hi @slayerjain 
Yes, I am working on this.

**Comment by RajGM** [comment]
Should I make changes to keploy UI first on UI repo, then come back and make changes here.
OR
Are we dynamically inserting filter category into the frontend?

**Comment by slayerjain** [comment]
@RajGM these filters are configured directly while initialisation of the SDK. So changes to the UI is not required

**Comment by Sarthak160** [comment]
closes with #80
