### ISSUE TITLE
request without testid in header are being recorded in "test" mode

### ISSUE THREAD

**Issue by re-Tick** [keploy/go-sdk#76]
**Describe the bug**
in test mode, the requests with no test-id in header are being recorded instead of running test.

**To Reproduce**
1. Run your local server on test mode.
2. Make a request to your API route without KEPLOY_TEST_ID in header
4. And the responses are recorded.

**Expected behavior**
The request should run a test instead of recorded.

**Comment by slayerjain** [comment]
@re-Tick as discussed this is expected behaviour
