### ISSUE TITLE
Echo + Gorm: `invalid character 'p' after top-level value`

### ISSUE THREAD

**Issue by sp35** [keploy/go-sdk#77]
**Describe the bug**
I'm trying to integrate keploy with an existing golang application:
- router: echo
- orm: gorm
- db: postgres

These are the configurations:
```golang
// keploy init
k := keploy.New(keploy.Config{
	App: keploy.AppConfig{
		Name: "myapp",
		Port: "1323",
	},
	Server: keploy.ServerConfig{
		URL: "http://localhost:8081",  // keploy server
	},
})
kecho.EchoV4(k, e)
```

```golang
// Register keploy sql driver to database/sql package.
driver := ksql.Driver{Driver: pq.Driver{}}
sql.Register("keploy", &driver)

// set DisableAutomaticPing to true
db, err := gorm.Open(postgres.New(postgres.Config{
	DriverName: "keploy",
	DSN:        dsn,
}), &gorm.Config{
	DisableAutomaticPing: true,
})
```
**Note**: I have skipped this: `set the context of *gorm.DB with request's context of http Handler function before queries.`; mentioned in gorm-gin example, as I wasn't sure what to pass in echo here. `WithContext` accepts `context.Context`, echo's request context is `echo.Context`. 

**Error**
```bash
failed to read testcases from keploy cloud      {"error": "invalid character 'p' after top-level value"}
github.com/keploy/go-sdk/keploy.(*Keploy).put
        /Users/sp35/***/vendor/github.com/keploy/go-sdk/keploy/keploy.go:360
```

**To Reproduce**
1. Use the configurations above and run with keploy in **record** mode
2. Hit a request
3. See error

**Expected behavior**
Test case is generated for the request.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey v12.0.1
 - Browser Chrome
 - Version 99.0.4844.84 (Official Build) (arm64)

**Comment by re-Tick** [comment]
Passing request context is important here because the mocked outputs of dependencies are stored in http request context.
@sp35 the request context is stored in echo.Context.Request().Context()

**Comment by re-Tick** [comment]
There was a mistake in gORM example of ReadME. Here, is the commit to fix it.
https://github.com/keploy/go-sdk/commit/15f7c45f31de5d07f3e73315d1f4074c74c70f90

**Comment by sp35** [comment]
Thank you for the quick response!
I'm passing the request context now, but I still get this error!

**Comment by re-Tick** [comment]
Interesting. Can you share your github repo.

**Comment by sp35** [comment]
The usual create, select, where and find methods.

**Comment by slayerjain** [comment]
@sp35 can we debug this on a quick call?

**Comment by sp35** [comment]
My bad, keploy server was on http://localhost:8081/api. Thanks for helping!
