### ISSUE TITLE
Create standard interfaces for routers

### ISSUE THREAD

**Issue by slayerjain** [keploy/go-sdk#79]
**Is your feature request related to a problem? Please describe.**
We can create standard interfaces for routers to extract various parameters and pass/extract context. This should simplify the addition of new routers. 

**Describe the solution you'd like**
The keploy framework should allow the implementation of standard interfaces for integrating routers. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by re-Tick** [comment]
Merged the changes. Closing this issue
