### ISSUE TITLE
security: update crypto package to fix GO-2021-0356

### ISSUE THREAD

**Issue by slayerjain** [keploy/go-sdk#93]
**Describe the bug**
The current version of crypto has the `GO-2021-0356` vulnerability. We need our version to fix it. more https://deps.dev/advisory/osv/GO-2021-0356

**Screenshots**

<img width="1480" alt="Screenshot 2022-07-06 at 10 13 32 AM" src="https://user-images.githubusercontent.com/12831254/177470331-b8fe8ad5-4c37-4110-aa81-c824bb531a1b.png">

**Comment by khanjasir90** [comment]
@slayerjain what I understood is that we just need to update the crypto packager version ! Is that so?

**Comment by slayerjain** [comment]
@khanjasir90 that should work

**Comment by khanjasir90** [comment]
any specific version or to the latest one?

**Comment by slayerjain** [comment]
I think the latest version should be fine. Hopefully it doesn't have any breaking changes :)

**Comment by khanjasir90** [comment]
cool will update the package to the latest one and raise the PR!
